= LibRed API
:imagesdir: ../images
:toc:
:toclevels: 3
:numbered:


== 概要

LibRed是Red解释器和运行时库的一个特殊版本，适合于集成到非Red语言开发的软件中。为了允许非Red软件与Red通信，libRed暴露一个极度底层的API(遵循C语言的cdecl或微软的stdcall标准)。它支持的特性有：

* 有能力从全局或局部上下文中设置/获取一个word的值。
* 大部分通用的Red数据类型的快捷构造器。
* 与宿主语言(通常是C语言)兼容的Red数据类型转换函数。
* 对宿主语言的一系列操作。
* 回调允许Red调用宿主函数。
* 面向控制台的调试函数。

术语：名词_host_表明宿主语言或者嵌入libRed的应用程序。

libRed使用例子可以在 https://github.com/red/red/tree/master/tests/libRed[这里]查看。

== 构建libRed

构建本地版本的libRed非常简单：
----
red build libRed
----
或者从Rebol的控制台和Red的源码中构建：
----
rc "build libRed"
----
这些命令行将会构建出适合于C语言的libRed版本(采用`cdecl`ABI)。如果你需要`stdcall`ABI(为了兼容微软的应用)，你需要运行：
----
red build libRed stdcall
----

== 值引用

Red值可以通过libRed函数调用被返回。它们被表示为32-bit的不透明引用。这些引用的生命周期都非常短，所以它们只适合于在局部范围内使用，比如传递一个引用到另一个函数调用。设置这些引用到宿主变量也是可以的，但是它应该在设置之后立即使用。这些引用都使用一个特定的内存管理器，这个管理器将仅仅保持引用在接下来的大约50次API调用内有效。例如：
----
long a, blk;

a = redSymbol("a");
redSet(a, redBlock(0));                   // returned reference is used immediately here

blk = redGet(a);
redPrint(blk);                            // safe reference usage

for(i = 0; i < 100, i++) {
    // redAppend(blk, redNone());         // unsafe reference usage!
    redAppend(redGet("a"), redNone());    // safe version
}
----


== C API

C API可以用在C/C++应用程序中，但是也可以集成Red到任何一种与C兼容的编程语言之中 https://en.wikipedia.org/wiki/Foreign_function_interface[FFI]。

=== 管理库

为了使用API中的函数，libRed_实例_需要被创建。

注意：当前，每个进程只允许单个libRed会话，预计将来允许对多实例的支持。

==== redOpen()
----
void redOpen(void)
----
初始化一个新的Red运行时库会话。 在调用任何其他API函数之前，必须调用此函数。 在同一个过程中可以安全地调用多次，只有一个会话将被打开。

注意：如果在`redOpen`之前调用了另一个函数，该函数的返回值将为`-2`，表示非法访问尝试。

==== redClose()
----
void redClose(void)
----
终止当前的Red运行时库会话，释放所有分配的资源。

=== Running Red code

主机软件可以直接运行Red代码，使用不同级别的控制，从文本形式提供Red代码进行评估，直接调用任何Red函数，以及传递在主机端构造的参数。

==== redDo()
----
red_value redDo(const char* source)
----
评估作为字符串传递的Red表达式，并返回最后一个Red值。

*例子*

----
redDo("a: 123");

redDo("view [text {hello}]");

char *s = (char *) malloc(100);
const char *caption = "Hello";
redDo(sprintf(s, "view [text \"%s\"]", caption));
----

==== redDoFile()
----
red_value redDoFile(const char* filename)
----
加载并评估文件名引用的Red脚本并返回最后一个Red值。文件名格式使用Red独立于操作系统的约定（基本上是Unix风格）。

*例子*

----
redDoFile("hello.red");
redDoFile("/c/dev/red/demo.red");
----

==== redDoBlock()
----
red_value redDoBlock(red_block code)
----
评估参数块并返回最后一个Red值。

*例子*

----
redDoBlock(redBlock(redWord("print"), redInteger(42)));
----

==== redCall()
----
red_value redCall(red_word name, ...)
----
调用名称字引用的Red函数（`any-function`类型），传递任何所需的参数（作为Red值）。 返回函数的最后一个Red值。 参数列表*必须*以“null”或“0”值终止，作为结束标记。

*例子*

----
redCall(redWord("random"), redInteger(6), 0);     // returns a random integer! value between 1 and 6
----

=== Registering a callback function

响应Red发生的事件，或将一些Red调用重定向到主机端（如重定向“打印”或“询问”）需要一种从Red方面调用主机功能的方法。 这可以使用`redRoutine（）`函数来实现。

==== redRoutine()
----
red_value redRoutine(red_word name, const char* spec, void* func_ptr)
----
定义为新的红色例程名称，以_spec_作为规范块，_func-ptr_ C函数指针为body。 C函数*必须*返回一个红色值（`redUnset（）`可以表示没有使用返回值）。

*例子*

----
#include "red.h"
#include <stdio.h>

red_integer add(red_integer a, red_integer b) {
    return redInteger(redCInt32(a) + redCInt32(b));
}

int main(void) {
    redRoutine(redWord("c-add"), "[a [integer!] b [integer!]]", (void*) &add);
    printf(redCInt32(redDo("c-add 2 3")));
    return 0;
}
----

=== Making Red values from C

来自libRary API的许多函数需要传递Red值（作为引用）。 以下函数是最常用数据类型的简单构造函数。

==== redSymbol()
----
long redSymbol(const char* word)
----
返回与加载的word（作为C字符串提供）相关联的符号ID。 然后可以将此ID传递到需要符号ID而不是字值的其他libRed API函数。

*例子*

----
long a = redSymbol("a");
redSet(a, redInteger(42));
printf("%l\n", redGet(a));
----

==== redUnset()
----
red_unset redUnset(void)
----
返回一个_unset!_值。

==== redNone()
----
red_none redNone(void)
----
返回一个_none!_值。

==== redLogic()
----
red_logic redLogic(long logic)
----
返回一个`logic !`值。 _logic_值为“0”，给出一个“false”值，所有其他值都赋值为“true”。

==== redDatatype()
----
red_datatype redDatatype(long type)
----
返回一个对应于_type_ ID的“datatype！”值，它是“RedType”枚举中的一个值。

==== redInteger()
----
red_integer redInteger(long number)
----
从数字返回一个“integer！”值。

==== redFloat()
----
red_float redFloat(double number)
----
从数字返回一个`float！`值。

==== redPair()
----
red_pair redPair(long x, long y)
----
从两个整数值返回一个`pair !`值。

==== redTuple()
----
red_tuple redTuple(long r, long g, long b)
----
从三个整数值（通常用于表示RGB颜色）返回一个`tuple！`值。 传递的参数将被截断为8位值。

==== redTuple4()
----
red_tuple redTuple4(long r, long g, long b, long a)
----
从四个整数值（通常用于表示RGBA颜色）返回一个`tuple！`值。 传递的参数将被截断为8位值。

==== redBinary()
----
red_binary redBinary(const char* buffer, long bytes)
----
从内存“缓冲区”指针返回一个“binary！”值，缓冲区的长度（以字节为单位）。 输入缓冲区将被内部复制。

==== redImage()
----
red_image redImage(long width, long height, const void* buffer, long format)
----
从内存`buffer`指针返回一个`image !`值。 图像的大小以“width”和“height”的形式定义。 输入缓冲区将被内部复制。 接受的缓冲区格式有：

* `RED_IMAGE_FORMAT_RGB`: 24-bit per pixel.
* `RED_IMAGE_FORMAT_ARGB`: 32-bit per pixel, alpha channel leading.

==== redString()
----
red_string redString(const char* string)
----
从字符串指针返回一个`string！`值。 参数字符串的默认预期编码为UTF-8。 其他编码可以使用`redSetEncoding（）`函数定义。

==== redWord()
----
red_word redWord(const char* word)
----
从C字符串返回一个`word !`值。 参数字符串的默认预期编码为UTF-8。 其他编码可以使用`redSetEncoding（）`函数定义。 不能以字样加载的字符串将返回“error！”值。

==== redBlock()
----
red_block redBlock(red_value v,...)
----

返回一个新的块！ 系列从参数列表构建。 列表*必须*以“null”或“0”值终止，作为结束标记。

*例子*

----
redBlock(0);                                  // Creates an empty block
redBlock(redInteger(42), redWord("hi"), 0);   // Creates [42 hi] block
----

==== redPath()
----
red_path redPath(red_value v, ...)
----

返回一条新path！系列从参数列表构建。 列表*必须*以“null”或“0”值终止，作为结束标记。

*例子*

----
redDo("a: [b 123]");
long res = redGetPath(redPath(redWord("a"), redWord("b"), 0));
printf("%l\n", redCInt32(res));    // will output 123
----

==== redLoadPath()
----
red_path redLoadPath(const char* path)
----

返回path！系列由一个表示为C字符串的路径构建。 这提供了一种构建路径的快速方法，而不单独构建每个元素。

*例子*

----
redGetPath(redLoadPath("a/b"));    // Creates and evaluates the a/b path! value.
----

==== redMakeSeries()
----
red_value redMakeSeries(unsigned long type, unsigned long slots)
----

返回一个新series！ 类型_类型_和足够的大小存储_slots_元素。 这是一个通用的系列构造函数。 该类型需要是“RedType”枚举值之一。

*例子*

----
redMakeSeries(RED_TYPE_PAREN, 2);  // Creates a paren! series

long path = redMakeSeries(RED_TYPE_SET_PATH, 2); // Creates a set-path!
redAppend(path, redWord("a"));
redAppend(path, redInteger(2));    // Now path is `a/2:`
----

=== Making C values from Red

将Red值转换为主机端是可能的，但受限于C语言中有限数量的类型。

==== redCInt32()
----
long redCInt32(red_integer number)
----

从红色整数返回一个32位有符号integer!值。

==== redCDouble()
----
double redCDouble(red_float number)
----

从Red float!返回一个C双精度浮点值。

==== redCString()
----
const char* redCString(red_string string)
----

从Red string!值返回一个UTF-8字符串缓冲区指针。 其他编码可以使用`redSetEncoding（）`函数定义。

==== redTypeOf()
----
long redTypeOf(red_value value)
----

返回Red值的类型ID。 类型ID值在“RedType”枚举中定义。 请参阅链接：link:libred.adoc＃_datatypes_definition[Datatypes] 部分。

=== Calling a Red action

可以使用`redCall'调用任何Red函数，但是对于最常见的操作，为了方便和更好的性能，提供了一些快捷方式。

==== redAppend()
----
red_value redAppend(red_series series, red_value value)
----

将_value_追加到_series_，并返回该系列。

==== redChange()
----
red_value redChange(red_series series, red_value value)
----

更改_series_中的_value_，并在更改的部分后返回序列。

==== redClear()
----
red_value redClear(red_series series)
----

从当前索引到尾部删除_series_值，并在新尾部返回系列。

==== redCopy()
----
red_value redCopy(red_value value)
----

返回非标量值的副本。

==== redFind()
----
red_value redFind(red_series series, red_value value)
----

返回找到值的系列，或NONE。

==== redIndex()
----
red_value redIndex(red_series series)
----

返回_series_相对于头的当前索引，或返回上下文中的单词。

==== redLength()
----
red_value redLength(red_series series)
----

返回_series_中从当前索引到尾部的值的数量。

==== redMake()
----
red_value redMake(red_value proto, red_value spec)
----

返回由_proto_类型的_spec_创建的新值。

==== redMold()
----
red_value redMold(red_value value)
----

返回值的源格式字符串表示形式。

==== redPick()
----
red_value redPick(red_series series, red_value value)
----

在给定的索引_value_上返回_series_。

==== redPoke()
----
red_value redPoke(red_series series, red_value index, red_value value)
----

使用_value_替换给定_index_上的_series_，并返回新值。

==== redPut()
----
red_value redPut(red_series series, red_value index, red_value value)
----

替换_series_或map中的键后面的值，并返回新值。

==== redRemove()
----
red_value redRemove(red_series series)
----

删除当前_series_索引的值，并在删除后返回序列号。

==== redSelect()
----
red_value redSelect(red_series series, red_value value)
----

在_series_中查找_value_并返回下一个值，或NONE。

==== redSkip()
----
red_value redSkip(red_series series, red_integer offset)
----

返回相对于当前索引的_series_。

==== redTo()
----
red_value redTo(red_value proto, red_value spec)
----

将_spec_值转换为_proto_指定的数据类型。

=== Accessing a Red word

设置Red字或获取Red字的值是在主机和Red运行时环境之间传递值的最直接方式。

==== redSet()
----
red_value redSet(long id, red_value value)
----

将从_id_符号定义的字设置为_value_。 从符号创建的词被绑定到全局上下文。 _value_由此函数返回。

==== redGet()
----
red_value redGet(long id)
----

返回从_id_符号定义的单词的值。 从符号创建的词被绑定到全局上下文。

=== Accessing a Red path

路径是非常灵活的方式来访问Red中的数据，因此他们在libRed中具有专用的访问器功能。 值得注意的是，它们允许访问对象上下文中的单词。

==== redSetPath()
----
red_value redSetPath(red_path path, red_value value)
----

将_path_设置为_value_并返回该_value。

==== redGetPath()
----
red_value redGetPath(red_path path)
----

返回_path_引用的_value_。

=== Accessing a Red object field

当对象的字段需要多个设置/访问时，直接使用对象值而不是构建路径更简单和更好。 以下两个功能是针对这种访问量身打造的。

注意：这些访问器可以使用任何其他关联的数组类型，而不仅仅是`object！`。 所以通过一个“map！”也是允许的。

==== redSetField()
----
red_value redSetField(red_value object, long field, red_value value)
----

将_object_的_field_设置为_value_并返回该_value。 _field_参数是使用`redSymbol（）`创建的符号ID。

==== redGetField()
----
red_value redGetField(red_value obj, long field)
----

返回存储在_object_的_field_中的_value_。 _field_参数是使用`redSymbol（）`创建的符号ID。

=== Debugging

还提供了一些方便的调试功能。 大多数需要输出的系统shell窗口，但是可以强制打开日志窗口，或将输出重定向到文件。

==== redPrint()
----
void redPrint(red_value value)
----

在标准输出上打印_value_，或打开调试控制台。

==== redProbe()
----
red_value redProbe(red_value value)
----

探测标准输出上的_value_，或者在调试控制台中打开。 该函数调用返回_value_。

==== redHasError()
----
red_value redHasError(void)
----

返回error!值，如果在以前的API调用中发生错误，或者如果没有发生错误则为null。

==== redFormError()
----
const char* redFormError(void)
----

如果发生错误，返回包含格式化错误的UTF-8字符串指针，如果没有发生错误，则返回“null”。

==== redOpenLogWindow()
----
int redOpenLogWindow(void)
----

打开日志窗口并将所有Red打印输出重定向到该窗口。 如果主机应用程序未从系统shell运行，则该功能非常有用，默认情况下，它是打印输出使用的。 如果日志窗口已经打开，多次调用此函数将不起作用。 成功返回“1”，失败时返回“0”。

注意：仅适用于Windows平台。

==== redCloseLogWindow()
----
int redCloseLogWindow(void)
----

关闭日志窗口。 当日志窗口已经关闭时调用此功能将不起作用。 成功返回“1”，失败时返回“0”。

注意：仅适用于Windows平台。

==== redOpenLogFile()
----
void redOpenLogFile(const string *name)
----

将Red打印功能的输出重定向到_name_指定的文件。 _name_中可以使用特定于OS的文件路径格式提供相对或绝对路径。

==== redCloseLogFile()
----
void redCloseLogFile(void)
----

关闭使用`redOpenLogFile（）'打开的日志文件。

注意：目前，日志文件*必须*在退出时关闭，否则会保留锁定，甚至可能导致某些主机（如MS Office应用程序）中的冻结或崩溃。

=== Datatypes definition

来自libRed API的一些功能可以引用Red数据类型：`redTypeOf（）`，`redMakeSeries（）`和`redDatatype（）`。 Red数据类型在主机端表示为枚举（`RedType`），其中类型是使用以下方案的名称：
----
RED_TYPE_<DATATYPE>
----

详尽的列表可以在 https://github.com/red/red/blob/master/libRed/red.h#L120[这里] 找到。

== Visual Basic API

Visual Basic API可用于VB和VBA（来自MS Office应用程序）。 它与C API基本相同，因此下面将仅描述差异。 差异主要在于各种功能，分为两种：

* `redBlock()`, `redPath()`, `redCall()` only accept Red values, and do not require a terminal `null` or `0` value, like the C version.
* `redBlockVB()`, `redPathVB()`, `redCallVB()` only accept VB values, which are automatically converted according to the following table:

[cols="1,4", options="header"]
|===
|VisualBasic | Red
|`vbInteger`| `integer!`
|`vbLong`| `integer!`
|`vbSingle`| `float!`
|`vbDouble`| `float!`
|`vbString`| `string!`
|===


==== Setting up

为了使用带有VB / VBA的libRed，您需要为“stdcall”ABI编译的libRed二进制版本。 如果您需要重新编译此类版本：
----
red build libRed stdcall
----

您还需要在项目中导入 https://github.com/red/red/blob/master/libRed/libRed.bas [`libRed.bas`] 模块文件。

==== redLogic()
----
Function redLogic(bool As Boolean) As Long
----
返回从VB `boolean`值构造的Red `logic！`值。

==== redBlockVB()
----
Function redBlockVB(ParamArray args() As Variant) As Long
----
返回一个新的block!系列从参数列表构建。 参数号是可变的，仅由VisualBasic值组成。

*例子*

----
redProbe redBlockVB()              ' Creates an empty block
redProbe redBlockVB(42, "hello")   ' Creates the [42 "hello" hi] block
----

==== redPathVB()
----
Function redPathVB(ParamArray args() As Variant) As Long
----

返回一条新path!系列从参数列表构建。 参数号是可变的，仅由VisualBasic值组成。

*例子*

----
redDo("a: [b 123]")
res = redGetPath(redPathVB("a", "b"))
Debug.print redCInt32(res))        ' will output 123
----

==== redCallVB()
----
Function redCallVB(ParamArray args() As Variant) As Long
----
调用由传递的字符串（第一个参数）引用的Red函数（“any-function！”类型），最后传递一些参数（作为VisualBasic值）。 返回函数的最后一个值。 参数号是可变的，仅由VisualBasic值组成。

*例子*

----
redCallVB("random", 6);            ' returns a random integer! value between 1 and 6
----

=== Registering a callback function

创建可以从Red侧调用的VisualBasic函数，就像C API一样，使用`redRoutine（）`调用。 该函数的最后一个参数是一个函数指针。 在VB中，这样的指针只能用于_module_中定义的函数，但不能在_UserForm_中获取。

这是Excel“Red Console”演示使用的回调：
----
Sub RegisterConsoleCB()
    redRoutine redWord("print"), "[msg [string!]]", AddressOf onConsolePrint
End Sub

Function onConsolePrint(ByVal msg As Long) As Long
    If redTypeOf(msg) <> red_unset Then Sheet2.AppendOutput redCString(msg)
    onConsolePrint = redUnset
End Function
----
